#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE "$DATABASE_NAME";
  CREATE USER "$DATABASE_USER" WITH ENCRYPTED PASSWORD '$DATABASE_PASS';
  GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_NAME" TO "$DATABASE_USER";
EOSQL
